use anyhow::{Context, Result};
use clap::Parser;
use data_ingestion_core::{process, to_format, ContractBuilderConfig, OutputFormat};
use std::path::{Path, PathBuf};

#[derive(Parser, Debug)]
#[command(
    name = "aytch",
    version = "0.1.0",
    about = "Data contract and data quality suite generator — ingest, analyze, and test data sources",
    after_help = "Examples:\n  aytch --action ingest --src schema.json --output ./contracts --type datacontract\n  aytch --action dataquality --src ./contracts --output ./expectations --type greatexpectations\n  aytch --action dqrun --src ./data/transactions.csv --tests ./expectations/transactions --output ./results --type greatexpectations\n  aytch --action dqrun --src ./data/ --tests ./expectations/ --contracts ./contracts/ --output ./results --recursive\n  aytch --action ingest --src ./schemas/ --output ./contracts --recursive"
)]
struct Cli {
    /// Action to perform: ingest, dataquality, or dqrun
    #[arg(long = "action", short = 'a', value_name = "ACTION",
          value_parser = ["ingest", "dataquality", "dqrun"])]
    action: Option<String>,

    // Deprecated aliases (kept for backward compatibility)
    /// [DEPRECATED] Use --action ingest instead
    #[arg(long = "ingest", short = 'i', hide = true)]
    ingest: bool,

    /// [DEPRECATED] Use --action dataquality instead
    #[arg(long = "dataquality", short = 'q', hide = true)]
    dataquality: bool,

    /// Path to source file or folder
    #[arg(long = "src", short = 's', value_name = "PATH")]
    src: Option<PathBuf>,

    /// Path to output directory
    #[arg(long = "output", short = 'o', value_name = "PATH")]
    output: Option<PathBuf>,

    /// Type of operation
    #[arg(long = "type", short = 't', value_name = "TYPE", default_value = "datacontract",
          value_parser = ["datacontract", "greatexpectations"])]
    contract_type: String,

    /// Output format(s): json, yaml, xml, csv, or all
    #[arg(long = "format", short = 'f', value_name = "FORMAT", default_value = "all")]
    format: String,

    /// Process all files in a folder recursively
    #[arg(long = "recursive", short = 'r')]
    recursive: bool,

    /// Skip the 1478 baseline tests (dataquality action only)
    #[arg(long = "no-baseline")]
    no_baseline: bool,

    /// Comma-separated list of suite names to include (dataquality action only)
    #[arg(long = "suites", value_name = "SUITES")]
    suites: Option<String>,

    /// Data contract owner metadata
    #[arg(long = "owner", value_name = "OWNER")]
    owner: Option<String>,

    /// Data contract domain metadata
    #[arg(long = "domain", value_name = "DOMAIN")]
    domain: Option<String>,

    /// Disable PII auto-detection
    #[arg(long = "no-pii")]
    no_pii: bool,

    /// Path to GX test suite files to execute (dqrun action only)
    /// Path to *_suite.json files generated by --action dataquality
    #[arg(long = "tests", value_name = "TESTS_PATH")]
    tests: Option<PathBuf>,

    /// Path to data contracts for auditing and pipeline traceability (dqrun action only)
    /// Path to *.contract.json files generated by --action ingest
    #[arg(long = "contracts", value_name = "CONTRACTS_PATH")]
    contracts: Option<PathBuf>,

    /// Python executable to use for dqrun (default: auto-detect from PATH)
    /// Use this to specify a virtualenv or conda Python that has great-expectations installed.
    /// Example: --python C:\venvs\gx\Scripts\python.exe
    /// Example: --python python3.11
    #[arg(long = "python", value_name = "PYTHON_EXE")]
    python: Option<String>,
}

fn main() {
    if let Err(e) = run() {
        eprintln!("Error: {:#}", e);
        std::process::exit(1);
    }
}

fn run() -> Result<()> {
    let cli = Cli::parse();

    // Resolve action from --action flag or deprecated aliases
    let action = resolve_action(&cli)?;

    match action.as_str() {
        "ingest" => run_ingest(&cli),
        "dataquality" => run_dataquality(&cli),
        "dqrun" => run_dqrun(&cli),
        "ingest+dataquality" => {
            run_ingest(&cli)?;
            run_dataquality(&cli)
        }
        _ => {
            eprintln!("Unknown action '{}'. Use: ingest, dataquality, dqrun", action);
            eprintln!("Run 'aytch --help' for usage.");
            std::process::exit(1);
        }
    }
}

fn resolve_action(cli: &Cli) -> Result<String> {
    match (&cli.action, cli.ingest, cli.dataquality) {
        (Some(action), false, false) => Ok(action.clone()),
        (None, true, false) => {
            eprintln!("⚠ Warning: --ingest is deprecated. Use --action ingest instead.");
            Ok("ingest".to_string())
        }
        (None, false, true) => {
            eprintln!("⚠ Warning: --dataquality is deprecated. Use --action dataquality instead.");
            Ok("dataquality".to_string())
        }
        (None, true, true) => {
            // Both deprecated flags: run ingest then dataquality
            eprintln!("⚠ Warning: --ingest and --dataquality are deprecated. Use --action ingest and --action dataquality separately.");
            Ok("ingest+dataquality".to_string())
        }
        (None, false, false) => {
            eprintln!("No action specified. Use --action <ingest|dataquality|dqrun>");
            eprintln!("Run 'aytch --help' for usage.");
            std::process::exit(1);
        }
        (Some(_), true, _) | (Some(_), _, true) => {
            anyhow::bail!("Cannot use --action with --ingest or --dataquality. Use --action only.")
        }
    }
}

// ── Ingest ────────────────────────────────────────────────────────────────────

fn run_ingest(cli: &Cli) -> Result<()> {
    // Validate required args
    let src = cli
        .src
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("--src is required for --action ingest. Specify the source file path."))?;
    let output_dir = cli
        .output
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("--output is required for --action ingest. Specify the output directory."))?;

    // Validate contract type
    if cli.contract_type != "datacontract" && cli.contract_type != "greatexpectations" {
        anyhow::bail!(
            "Unknown --type '{}'. Use: datacontract or greatexpectations",
            cli.contract_type
        );
    }

    // Collect source files (supports --recursive for directories)
    let files = collect_source_files(src, cli.recursive)?;

    println!("⟳ Ingesting {} file(s)...", files.len());

    // Create output directory
    std::fs::create_dir_all(output_dir)
        .with_context(|| format!("Cannot create output directory: {}", output_dir.display()))?;

    for file_path in &files {
        ingest_single_file(file_path, output_dir, cli)?;
    }

    println!(
        "\nDone. Contract file(s) written to {}",
        output_dir.display()
    );
    Ok(())
}

fn ingest_single_file(src: &Path, output_dir: &Path, cli: &Cli) -> Result<()> {
    // Validate source file exists
    if !src.exists() {
        anyhow::bail!("Source file not found: {}", src.display());
    }
    if !src.is_file() {
        anyhow::bail!("Source path is not a file: {}", src.display());
    }

    // Read source file
    let content = std::fs::read(src)
        .with_context(|| format!("Failed to read source file: {}", src.display()))?;

    // Get source path string for format detection
    let src_path_str = src.to_string_lossy();
    let src_stem = src
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("contract");

    println!("  ⟳ Ingesting: {}", src.display());

    // Build config
    let config = ContractBuilderConfig {
        version: "1.0.0".to_string(),
        owner: cli.owner.clone(),
        domain: cli.domain.clone(),
        enrich_pii: !cli.no_pii,
        include_nested: true,
        ..Default::default()
    };

    // Process
    let contract = process(&content, None, Some(&src_path_str), config)
        .map_err(|e| anyhow::anyhow!("Failed to ingest {}: {}", src.display(), e))?;

    println!(
        "  ✓ Contract: \"{}\" — {} fields",
        contract.name,
        contract.fields.len()
    );

    // Determine which formats to write
    let formats = resolve_formats(&cli.format)?;

    let mut written = 0;
    for (fmt, ext) in &formats {
        let bytes = to_format(&contract, fmt.clone())
            .map_err(|e| anyhow::anyhow!("Serialization to {} failed: {}", ext, e))?;

        let filename = format!("{}.contract.{}", src_stem, ext);
        let out_path = output_dir.join(&filename);

        std::fs::write(&out_path, &bytes)
            .with_context(|| format!("Failed to write {}", out_path.display()))?;

        println!("  ✓ Written: {}", out_path.display());
        written += 1;
    }

    println!(
        "  ✓ {} contract file{} written",
        written,
        if written == 1 { "" } else { "s" }
    );

    Ok(())
}

// ── Data Quality ──────────────────────────────────────────────────────────────

fn run_dataquality(cli: &Cli) -> Result<()> {
    let src = cli
        .src
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("--src is required for --action dataquality"))?;
    let output_dir = cli
        .output
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("--output is required for --action dataquality"))?;

    // Collect source files
    let files = collect_source_files(src, cli.recursive)?;

    println!("⟳ Generating data quality suites for {} file(s)...", files.len());

    for file_path in &files {
        process_dataquality_file(file_path, output_dir, cli)?;
    }

    println!("\nDone. Data quality suites written to {}", output_dir.display());
    Ok(())
}

fn process_dataquality_file(src: &Path, output_dir: &Path, cli: &Cli) -> Result<()> {
    use data_quality_core::{
        generate_all_suites, serialize_suite_set, DqConfig, DqOutputFormat,
    };

    let src_stem = src.file_stem().and_then(|s| s.to_str()).unwrap_or("contract");
    let content = std::fs::read(src)
        .with_context(|| format!("Failed to read source file: {}", src.display()))?;
    let src_path_str = src.to_string_lossy();

    // Step 1: Ingest source → DataContract
    println!("  ⟳ Ingesting: {}", src.display());
    let ingest_config = ContractBuilderConfig {
        owner: cli.owner.clone(),
        domain: cli.domain.clone(),
        enrich_pii: !cli.no_pii,
        ..Default::default()
    };
    let contract = process(&content, None, Some(&src_path_str), ingest_config)
        .map_err(|e| anyhow::anyhow!("Failed to ingest {}: {}", src.display(), e))?;

    // Step 2: Build DqConfig
    let enabled_suites = cli.suites.as_ref().map(|s| {
        s.split(',')
            .map(|x| x.trim().to_string())
            .collect::<Vec<_>>()
    });
    let dq_config = DqConfig {
        include_baseline: !cli.no_baseline,
        include_contract_specific: true,
        enabled_suites,
        ..Default::default()
    };

    // Step 3: Generate suites
    let suite_set = generate_all_suites(&contract, &dq_config);
    let total = suite_set.total_test_count;
    println!(
        "  ✓ Generated {} test suites ({} tests) for \"{}\"",
        suite_set.baseline_suites.len() + suite_set.contract_suites.len(),
        total,
        contract.name
    );

    // Step 4: Write output files
    let contract_output_dir = output_dir.join(src_stem);
    std::fs::create_dir_all(&contract_output_dir)?;

    let output_files = serialize_suite_set(&suite_set, DqOutputFormat::GxJson)
        .map_err(|e| anyhow::anyhow!("Serialization failed: {}", e))?;

    let contract_name_slug = contract.name.to_lowercase().replace(' ', "_");

    for file in &output_files {
        // Determine subdirectory: baseline/ or contract_specific/ or root
        let subdir = if file.filename.starts_with("manifest") || file.filename.starts_with("summary") {
            contract_output_dir.clone()
        } else if file.suite_name.contains(&contract_name_slug) {
            contract_output_dir.join("contract_specific")
        } else {
            contract_output_dir.join("baseline")
        };
        std::fs::create_dir_all(&subdir)?;

        // The filename from serialize_suite_set includes path components like
        // "order/baseline/data_validity_suite.json" — extract just the basename
        let basename = Path::new(&file.filename)
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or(&file.filename);

        let out_path = subdir.join(basename);
        std::fs::write(&out_path, &file.content)?;
        println!("  ✓ Written: {}", out_path.display());
    }

    Ok(())
}

// ── DQ Run ────────────────────────────────────────────────────────────────────

fn run_dqrun(cli: &Cli) -> Result<()> {
    let src = cli.src.as_ref()
        .ok_or_else(|| anyhow::anyhow!(
            "--src is required for --action dqrun\n\
             Specify the data file(s) to validate (e.g. --src ./data/transactions.csv)"
        ))?;
    let tests_path = cli.tests.as_ref()
        .ok_or_else(|| anyhow::anyhow!(
            "--tests is required for --action dqrun\n\
             Specify the path to GX suite files generated by --action dataquality\n\
             Example: --tests ./expectations/transactions"
        ))?;
    let output_dir = cli.output.as_ref()
        .ok_or_else(|| anyhow::anyhow!(
            "--output is required for --action dqrun\n\
             Specify where to write validation results"
        ))?;

    if cli.contract_type != "greatexpectations" {
        anyhow::bail!("--action dqrun currently only supports --type greatexpectations");
    }

    // Validate src exists
    if !src.exists() {
        anyhow::bail!("Source data path does not exist: {}", src.display());
    }

    // Collect GX suite JSON files from --tests
    let suite_files = collect_source_files(tests_path, cli.recursive)?
        .into_iter()
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("json"))
        .filter(|p| {
            let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
            name.ends_with("_suite.json")
        })
        .collect::<Vec<_>>();

    if suite_files.is_empty() {
        anyhow::bail!(
            "No GX suite files (*_suite.json) found in: {}\n\
             Generate them first with: aytch --action dataquality --src <contracts> --output <tests_dir> --type greatexpectations",
            tests_path.display()
        );
    }

    // Collect data source files from --src
    let data_files = collect_source_files(src, cli.recursive)?
        .into_iter()
        .filter(|p| {
            matches!(
                p.extension().and_then(|e| e.to_str()),
                Some("csv") | Some("json") | Some("xlsx") | Some("xls") | Some("parquet")
            )
        })
        .collect::<Vec<_>>();

    if data_files.is_empty() {
        anyhow::bail!(
            "No supported data files found in: {}\n\
             Supported formats: .csv, .json, .xlsx, .parquet",
            src.display()
        );
    }

    std::fs::create_dir_all(output_dir)?;

    println!("⟳ Running {} GX suite(s) against {} data file(s)", suite_files.len(), data_files.len());
    println!("  Tests:    {}", tests_path.display());
    println!("  Data:     {}", src.display());
    if let Some(contracts) = &cli.contracts {
        println!("  Contracts: {}", contracts.display());
    }
    println!("  Output:   {}", output_dir.display());

    // Build and execute the Python runner script
    let runner_script = build_gx_runner_script(&suite_files, &data_files, output_dir, cli.contracts.as_deref())?;
    let script_path = output_dir.join("_aytch_gx_runner.py");
    std::fs::write(&script_path, &runner_script)?;

    let python_cmd = find_python(cli.python.as_deref())?;
    println!("  Python:   {}", python_cmd);

    let status = std::process::Command::new(&python_cmd)
        .arg(&script_path)
        .status()
        .with_context(|| format!("Failed to execute Python: {}", python_cmd))?;

    let _ = std::fs::remove_file(&script_path);

    if !status.success() {
        anyhow::bail!("GX execution failed with exit code: {:?}", status.code());
    }

    println!("\n✓ GX validation complete. Results written to: {}", output_dir.display());
    Ok(())
}

// ── DQ Run helpers ────────────────────────────────────────────────────────────

/// Find Python executable on PATH, or use the user-specified override.
fn find_python(override_cmd: Option<&str>) -> Result<String> {
    // If the user specified --python, validate it and use it directly.
    if let Some(cmd) = override_cmd {
        if std::process::Command::new(cmd)
            .arg("--version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
        {
            return Ok(cmd.to_string());
        }
        anyhow::bail!(
            "Specified Python executable not found or not executable: {}\n\
             Check the path and ensure Python is installed there.",
            cmd
        );
    }

    // Auto-detect from PATH.
    for cmd in &["python", "python3", "py"] {
        if std::process::Command::new(cmd)
            .arg("--version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
        {
            return Ok(cmd.to_string());
        }
    }
    anyhow::bail!(
        "Python not found on PATH. Install Python 3.9+ and ensure it is on your PATH.\n\
         Alternatively, specify the Python executable with --python <path>.\n\
         Download: https://www.python.org/downloads/"
    )
}

/// Build a Python script that runs GX suites against data files
fn build_gx_runner_script(
    suite_files: &[PathBuf],
    data_files: &[PathBuf],
    output_dir: &Path,
    contracts_path: Option<&Path>,
) -> Result<String> {
    let suite_paths_json = serde_json::to_string(
        &suite_files.iter()
            .map(|p| p.to_string_lossy().replace('\\', "/"))
            .collect::<Vec<_>>()
    )?;

    let data_files_json = serde_json::to_string(
        &data_files.iter()
            .map(|p| p.to_string_lossy().replace('\\', "/"))
            .collect::<Vec<_>>()
    )?;

    let output_dir_str = output_dir.to_string_lossy().replace('\\', "/");
    let contracts_path_str = contracts_path
        .map(|p| format!("\"{}\"", p.to_string_lossy().replace('\\', "/")))
        .unwrap_or_else(|| "None".to_string());

    Ok(format!(r#"#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
aytch dqrun -- Great Expectations suite executor (GX 1.x API)
Auto-generated by aytch. Do not edit manually.
"""
import sys
import json
import os
from pathlib import Path
from datetime import datetime

# Ensure stdout uses UTF-8 on Windows (avoids cp1252 UnicodeEncodeError)
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
if hasattr(sys.stderr, 'reconfigure'):
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')

# Check great_expectations is installed (GX 1.x)
try:
    import great_expectations as gx
    import great_expectations.expectations as gxe
except ImportError:
    print("ERROR: great_expectations is not installed.")
    print("Install it with: pip install great-expectations")
    print("Or: pip install -r requirements-dev.txt")
    sys.exit(1)

# Check pandas is installed (needed for PandasExecutionEngine)
try:
    import pandas as pd
except ImportError:
    print("ERROR: pandas is not installed.")
    print("Install it with: pip install pandas")
    sys.exit(1)

SUITE_FILES = {suite_paths_json}
DATA_FILES = {data_files_json}
OUTPUT_DIR = "{output_dir_str}"
CONTRACTS_PATH = {contracts_path_str}

def snake_to_pascal(name: str) -> str:
    """Convert expect_column_to_exist -> ExpectColumnToExist"""
    return ''.join(word.capitalize() for word in name.split('_'))

def load_suite_into_context(context, suite_file: str, suite_index: int):
    """Load a GX ExpectationSuite from a JSON file and register it with the context."""
    with open(suite_file, 'r', encoding='utf-8') as f:
        suite_dict = json.load(f)

    # Use a unique name per suite+index to avoid collisions across runs
    base_name = suite_dict.get('name', Path(suite_file).stem)
    suite_name = f"{{base_name}}_{{suite_index}}"

    suite = context.suites.add(gx.ExpectationSuite(name=suite_name))

    added = 0
    skipped = 0
    for exp_dict in suite_dict.get('expectations', []):
        exp_type = exp_dict.get('type', exp_dict.get('expectation_type', ''))
        kwargs = exp_dict.get('kwargs', {{}})

        if not exp_type:
            skipped += 1
            continue

        # Convert snake_case type to PascalCase class name
        class_name = snake_to_pascal(exp_type)
        exp_class = getattr(gxe, class_name, None)
        if exp_class is None:
            skipped += 1
            continue

        try:
            expectation = exp_class(**kwargs)
            suite.add_expectation(expectation)
            added += 1
        except Exception as e:
            skipped += 1

    return suite, added, skipped

def run_suite_against_df(context, suite, df: "pd.DataFrame", run_index: int) -> dict:
    """Run a GX suite against a DataFrame using ephemeral context."""
    ds_name = f"aytch_source_{{run_index}}"
    asset_name = f"aytch_asset_{{run_index}}"
    batch_name = f"aytch_batch_{{run_index}}"
    vd_name = f"aytch_vd_{{suite.name}}"

    data_source = context.data_sources.add_pandas(name=ds_name)
    data_asset = data_source.add_dataframe_asset(name=asset_name)
    batch_definition = data_asset.add_batch_definition_whole_dataframe(batch_name)

    validation_definition = context.validation_definitions.add(
        gx.ValidationDefinition(
            name=vd_name,
            data=batch_definition,
            suite=suite,
        )
    )

    results = validation_definition.run(
        batch_parameters={{"dataframe": df}}
    )
    return results.to_json_dict()

def load_dataframe(data_path: Path) -> "pd.DataFrame":
    """Load a data file into a DataFrame based on its extension."""
    ext = data_path.suffix.lower()
    if ext == '.csv':
        return pd.read_csv(data_path)
    elif ext == '.json':
        return pd.read_json(data_path)
    elif ext in ('.xlsx', '.xls'):
        return pd.read_excel(data_path)
    elif ext == '.parquet':
        return pd.read_parquet(data_path)
    else:
        raise ValueError(f"Unsupported data format: {{ext}}. Supported: .csv, .json, .xlsx, .parquet")

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    all_results = {{
        "run_timestamp": datetime.utcnow().isoformat() + "Z",
        "gx_version": gx.__version__,
        "data_files": DATA_FILES,
        "suite_count": len(SUITE_FILES),
        "contracts_path": CONTRACTS_PATH,
        "suites": []
    }}

    total_expectations = 0
    total_passed = 0
    total_failed = 0
    run_index = 0

    for data_file in DATA_FILES:
        data_path = Path(data_file)
        print(f"\nLoading data: {{data_path}}")

        try:
            df = load_dataframe(data_path)
        except Exception as e:
            print(f"  ERROR loading {{data_path}}: {{e}}")
            continue

        print(f"  Rows: {{len(df)}}, Columns: {{len(df.columns)}}")
        print(f"  Columns: {{list(df.columns)}}")

        for suite_idx, suite_file in enumerate(SUITE_FILES):
            suite_name = Path(suite_file).stem
            data_stem = data_path.stem
            print(f"\n  Running suite: {{suite_name}} against {{data_stem}}")

            # Each suite run needs a fresh ephemeral context to avoid name collisions
            context = gx.get_context(mode="ephemeral")

            try:
                suite, added, skipped = load_suite_into_context(context, suite_file, run_index)
                exp_count = added
                print(f"    Expectations loaded: {{added}} (skipped: {{skipped}})")

                if exp_count == 0:
                    print(f"    SKIP: no runnable expectations in suite")
                    all_results["suites"].append({{
                        "data_file": data_file,
                        "suite_name": suite_name,
                        "suite_file": suite_file,
                        "success": True,
                        "expectations_total": 0,
                        "expectations_passed": 0,
                        "expectations_failed": 0,
                        "skipped": True
                    }})
                    run_index += 1
                    continue

                results = run_suite_against_df(context, suite, df, run_index)

                passed = results.get('statistics', {{}}).get('successful_expectations', 0)
                failed = results.get('statistics', {{}}).get('unsuccessful_expectations', 0)
                success = results.get('success', False)

                total_expectations += exp_count
                total_passed += passed
                total_failed += failed

                status = "✓ PASSED" if success else "✗ FAILED"
                print(f"    {{status}}: {{passed}}/{{exp_count}} expectations passed")

                # Write per-suite results (namespaced by data file stem)
                suite_result_file = Path(OUTPUT_DIR) / f"{{data_stem}}_{{suite_name}}_results.json"
                with open(suite_result_file, 'w', encoding='utf-8') as f:
                    json.dump(results, f, indent=2, default=str)

                all_results["suites"].append({{
                    "data_file": data_file,
                    "suite_name": suite_name,
                    "suite_file": suite_file,
                    "success": success,
                    "expectations_total": exp_count,
                    "expectations_passed": passed,
                    "expectations_failed": failed,
                    "results_file": str(suite_result_file)
                }})

            except Exception as e:
                import traceback
                print(f"    ERROR running suite {{suite_name}}: {{e}}")
                traceback.print_exc()
                all_results["suites"].append({{
                    "data_file": data_file,
                    "suite_name": suite_name,
                    "suite_file": suite_file,
                    "success": False,
                    "error": str(e)
                }})

            run_index += 1

    # Summary
    all_results["total_expectations"] = total_expectations
    all_results["total_passed"] = total_passed
    all_results["total_failed"] = total_failed
    all_results["overall_success"] = total_failed == 0

    # Write summary
    summary_file = Path(OUTPUT_DIR) / "validation_summary.json"
    with open(summary_file, 'w', encoding='utf-8') as f:
        json.dump(all_results, f, indent=2, default=str)

    print(f"\n{{'='*60}}")
    print(f"VALIDATION SUMMARY")
    print(f"{{'='*60}}")
    print(f"GX version:          {{gx.__version__}}")
    print(f"Data files:          {{len(DATA_FILES)}}")
    print(f"Suites run:          {{len(SUITE_FILES)}}")
    print(f"Total expectations:  {{total_expectations}}")
    print(f"Passed:              {{total_passed}}")
    print(f"Failed:              {{total_failed}}")
    if CONTRACTS_PATH:
        print(f"Contracts:           {{CONTRACTS_PATH}}")
    overall = "✓ ALL PASSED" if total_failed == 0 else f"✗ {{total_failed}} FAILED"
    print(f"Overall:             {{overall}}")
    print(f"Results written to:  {{OUTPUT_DIR}}")
    print(f"Summary:             {{summary_file}}")

    sys.exit(0 if total_failed == 0 else 1)

if __name__ == '__main__':
    main()
"#))
}

// ── File collection ───────────────────────────────────────────────────────────

fn collect_source_files(src: &Path, recursive: bool) -> Result<Vec<PathBuf>> {
    if src.is_file() {
        return Ok(vec![src.to_path_buf()]);
    }
    if src.is_dir() {
        let extensions = ["json", "yaml", "yml", "xml", "xsd", "csv"];
        let mut files = Vec::new();
        collect_files_in_dir(src, &extensions, recursive, &mut files)?;
        if files.is_empty() {
            anyhow::bail!("No supported files found in directory: {}", src.display());
        }
        return Ok(files);
    }
    anyhow::bail!("Source path does not exist: {}", src.display())
}

fn collect_files_in_dir(
    dir: &Path,
    extensions: &[&str],
    recursive: bool,
    files: &mut Vec<PathBuf>,
) -> Result<()> {
    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_file() {
            if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                if extensions.contains(&ext.to_lowercase().as_str()) {
                    files.push(path);
                }
            }
        } else if path.is_dir() && recursive {
            collect_files_in_dir(&path, extensions, recursive, files)?;
        }
    }
    Ok(())
}

// ── Format resolution ─────────────────────────────────────────────────────────

fn resolve_formats(format_str: &str) -> Result<Vec<(OutputFormat, &'static str)>> {
    match format_str.to_lowercase().as_str() {
        "all" => Ok(vec![
            (OutputFormat::Json, "json"),
            (OutputFormat::Yaml, "yaml"),
            (OutputFormat::Xml, "xml"),
            (OutputFormat::Csv, "csv"),
        ]),
        "json" => Ok(vec![(OutputFormat::Json, "json")]),
        "yaml" => Ok(vec![(OutputFormat::Yaml, "yaml")]),
        "xml" => Ok(vec![(OutputFormat::Xml, "xml")]),
        "csv" => Ok(vec![(OutputFormat::Csv, "csv")]),
        other => anyhow::bail!(
            "Unknown --format '{}'. Use: json, yaml, xml, csv, or all",
            other
        ),
    }
}
