use anyhow::{Context, Result};
use clap::Parser;
use data_ingestion_core::{process, to_format, ContractBuilderConfig, OutputFormat};
use std::path::{Path, PathBuf};

#[derive(Parser, Debug)]
#[command(
    name = "aytch",
    version = "0.1.0",
    about = "Data contract and data quality suite generator — ingest, analyze, and test data sources",
    after_help = "Examples:\n  aytch --action ingest --src schema.json --output ./contracts --type datacontract\n  aytch --action dataquality --src ./contracts --output ./expectations --type greatexpectations\n  aytch --action dqrun --src ./data/transactions.csv --tests ./expectations/transactions --output ./results --type greatexpectations\n  aytch --action dqrun --src ./data/ --tests ./expectations/ --contracts ./contracts/ --output ./results --recursive\n  aytch --action ingest --src ./schemas/ --output ./contracts --recursive"
)]
struct Cli {
    /// Action to perform: ingest, dataquality, or dqrun
    #[arg(long = "action", short = 'a', value_name = "ACTION",
          value_parser = ["ingest", "dataquality", "dqrun"])]
    action: Option<String>,

    // Deprecated aliases (kept for backward compatibility)
    /// [DEPRECATED] Use --action ingest instead
    #[arg(long = "ingest", short = 'i', hide = true)]
    ingest: bool,

    /// [DEPRECATED] Use --action dataquality instead
    #[arg(long = "dataquality", short = 'q', hide = true)]
    dataquality: bool,

    /// Path to source file or folder
    #[arg(long = "src", short = 's', value_name = "PATH")]
    src: Option<PathBuf>,

    /// Path to output directory
    #[arg(long = "output", short = 'o', value_name = "PATH")]
    output: Option<PathBuf>,

    /// Type of operation
    #[arg(long = "type", short = 't', value_name = "TYPE", default_value = "datacontract",
          value_parser = ["datacontract", "greatexpectations"])]
    contract_type: String,

    /// Output format(s): json, yaml, xml, csv, or all
    #[arg(long = "format", short = 'f', value_name = "FORMAT", default_value = "all")]
    format: String,

    /// Process all files in a folder recursively
    #[arg(long = "recursive", short = 'r')]
    recursive: bool,

    /// Skip the 1478 baseline tests (dataquality action only)
    #[arg(long = "no-baseline")]
    no_baseline: bool,

    /// Comma-separated list of suite names to include (dataquality action only)
    #[arg(long = "suites", value_name = "SUITES")]
    suites: Option<String>,

    /// Data contract owner metadata
    #[arg(long = "owner", value_name = "OWNER")]
    owner: Option<String>,

    /// Data contract domain metadata
    #[arg(long = "domain", value_name = "DOMAIN")]
    domain: Option<String>,

    /// Disable PII auto-detection
    #[arg(long = "no-pii")]
    no_pii: bool,

    /// Path to GX test suite files to execute (dqrun action only)
    /// Path to *_suite.json files generated by --action dataquality
    #[arg(long = "tests", value_name = "TESTS_PATH")]
    tests: Option<PathBuf>,

    /// Path to data contracts for auditing and pipeline traceability (dqrun action only)
    /// Path to *.contract.json files generated by --action ingest
    #[arg(long = "contracts", value_name = "CONTRACTS_PATH")]
    contracts: Option<PathBuf>,

    /// Python executable to use for dqrun (default: auto-detect from PATH)
    /// Use this to specify a virtualenv or conda Python that has great-expectations installed.
    /// Example: --python C:\venvs\gx\Scripts\python.exe
    /// Example: --python python3.11
    #[arg(long = "python", value_name = "PYTHON_EXE")]
    python: Option<String>,
}

fn main() {
    if let Err(e) = run() {
        eprintln!("Error: {:#}", e);
        std::process::exit(1);
    }
}

fn run() -> Result<()> {
    let cli = Cli::parse();

    // Resolve action from --action flag or deprecated aliases
    let action = resolve_action(&cli)?;

    match action.as_str() {
        "ingest" => run_ingest(&cli),
        "dataquality" => run_dataquality(&cli),
        "dqrun" => run_dqrun(&cli),
        "ingest+dataquality" => {
            run_ingest(&cli)?;
            run_dataquality(&cli)
        }
        _ => {
            eprintln!("Unknown action '{}'. Use: ingest, dataquality, dqrun", action);
            eprintln!("Run 'aytch --help' for usage.");
            std::process::exit(1);
        }
    }
}

fn resolve_action(cli: &Cli) -> Result<String> {
    match (&cli.action, cli.ingest, cli.dataquality) {
        (Some(action), false, false) => Ok(action.clone()),
        (None, true, false) => {
            eprintln!("⚠ Warning: --ingest is deprecated. Use --action ingest instead.");
            Ok("ingest".to_string())
        }
        (None, false, true) => {
            eprintln!("⚠ Warning: --dataquality is deprecated. Use --action dataquality instead.");
            Ok("dataquality".to_string())
        }
        (None, true, true) => {
            // Both deprecated flags: run ingest then dataquality
            eprintln!("⚠ Warning: --ingest and --dataquality are deprecated. Use --action ingest and --action dataquality separately.");
            Ok("ingest+dataquality".to_string())
        }
        (None, false, false) => {
            eprintln!("No action specified. Use --action <ingest|dataquality|dqrun>");
            eprintln!("Run 'aytch --help' for usage.");
            std::process::exit(1);
        }
        (Some(_), true, _) | (Some(_), _, true) => {
            anyhow::bail!("Cannot use --action with --ingest or --dataquality. Use --action only.")
        }
    }
}

// ── Ingest ────────────────────────────────────────────────────────────────────

fn run_ingest(cli: &Cli) -> Result<()> {
    // Validate required args
    let src = cli
        .src
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("--src is required for --action ingest. Specify the source file path."))?;
    let output_dir = cli
        .output
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("--output is required for --action ingest. Specify the output directory."))?;

    // Validate contract type
    if cli.contract_type != "datacontract" && cli.contract_type != "greatexpectations" {
        anyhow::bail!(
            "Unknown --type '{}'. Use: datacontract or greatexpectations",
            cli.contract_type
        );
    }

    // Collect source files (supports --recursive for directories)
    let files = collect_source_files(src, cli.recursive)?;

    println!("⟳ Ingesting {} file(s)...", files.len());

    // Create output directory
    std::fs::create_dir_all(output_dir)
        .with_context(|| format!("Cannot create output directory: {}", output_dir.display()))?;

    for file_path in &files {
        ingest_single_file(file_path, output_dir, cli)?;
    }

    println!(
        "\nDone. Contract file(s) written to {}",
        output_dir.display()
    );
    Ok(())
}

fn ingest_single_file(src: &Path, output_dir: &Path, cli: &Cli) -> Result<()> {
    // Validate source file exists
    if !src.exists() {
        anyhow::bail!("Source file not found: {}", src.display());
    }
    if !src.is_file() {
        anyhow::bail!("Source path is not a file: {}", src.display());
    }

    // Read source file
    let content = std::fs::read(src)
        .with_context(|| format!("Failed to read source file: {}", src.display()))?;

    // Get source path string for format detection
    let src_path_str = src.to_string_lossy();
    let src_stem = src
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("contract");

    println!("  ⟳ Ingesting: {}", src.display());

    // Build config
    let config = ContractBuilderConfig {
        version: "1.0.0".to_string(),
        owner: cli.owner.clone(),
        domain: cli.domain.clone(),
        enrich_pii: !cli.no_pii,
        include_nested: true,
        ..Default::default()
    };

    // Process
    let contract = process(&content, None, Some(&src_path_str), config)
        .map_err(|e| anyhow::anyhow!("Failed to ingest {}: {}", src.display(), e))?;

    println!(
        "  ✓ Contract: \"{}\" — {} fields",
        contract.name,
        contract.fields.len()
    );

    // Determine which formats to write
    let formats = resolve_formats(&cli.format)?;

    let mut written = 0;
    for (fmt, ext) in &formats {
        let bytes = to_format(&contract, fmt.clone())
            .map_err(|e| anyhow::anyhow!("Serialization to {} failed: {}", ext, e))?;

        let filename = format!("{}.contract.{}", src_stem, ext);
        let out_path = output_dir.join(&filename);

        std::fs::write(&out_path, &bytes)
            .with_context(|| format!("Failed to write {}", out_path.display()))?;

        println!("  ✓ Written: {}", out_path.display());
        written += 1;
    }

    println!(
        "  ✓ {} contract file{} written",
        written,
        if written == 1 { "" } else { "s" }
    );

    Ok(())
}

// ── Data Quality ──────────────────────────────────────────────────────────────

fn run_dataquality(cli: &Cli) -> Result<()> {
    let src = cli
        .src
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("--src is required for --action dataquality"))?;
    let output_dir = cli
        .output
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("--output is required for --action dataquality"))?;

    // Collect source files
    let files = collect_source_files(src, cli.recursive)?;

    println!("⟳ Generating data quality suites for {} file(s)...", files.len());

    for file_path in &files {
        process_dataquality_file(file_path, output_dir, cli)?;
    }

    println!("\nDone. Data quality suites written to {}", output_dir.display());
    Ok(())
}

fn process_dataquality_file(src: &Path, output_dir: &Path, cli: &Cli) -> Result<()> {
    use data_quality_core::{
        generate_all_suites, serialize_suite_set, DqConfig, DqOutputFormat,
    };

    let src_stem = src.file_stem().and_then(|s| s.to_str()).unwrap_or("contract");
    let content = std::fs::read(src)
        .with_context(|| format!("Failed to read source file: {}", src.display()))?;
    let src_path_str = src.to_string_lossy();

    // Step 1: Ingest source → DataContract
    println!("  ⟳ Ingesting: {}", src.display());
    let ingest_config = ContractBuilderConfig {
        owner: cli.owner.clone(),
        domain: cli.domain.clone(),
        enrich_pii: !cli.no_pii,
        ..Default::default()
    };
    let contract = process(&content, None, Some(&src_path_str), ingest_config)
        .map_err(|e| anyhow::anyhow!("Failed to ingest {}: {}", src.display(), e))?;

    // Step 2: Build DqConfig
    let enabled_suites = cli.suites.as_ref().map(|s| {
        s.split(',')
            .map(|x| x.trim().to_string())
            .collect::<Vec<_>>()
    });
    let dq_config = DqConfig {
        include_baseline: !cli.no_baseline,
        include_contract_specific: true,
        enabled_suites,
        ..Default::default()
    };

    // Step 3: Generate suites
    let suite_set = generate_all_suites(&contract, &dq_config);
    let total = suite_set.total_test_count;
    println!(
        "  ✓ Generated {} test suites ({} tests) for \"{}\"",
        suite_set.baseline_suites.len() + suite_set.contract_suites.len(),
        total,
        contract.name
    );

    // Step 4: Write output files
    let contract_output_dir = output_dir.join(src_stem);
    std::fs::create_dir_all(&contract_output_dir)?;

    let output_files = serialize_suite_set(&suite_set, DqOutputFormat::GxJson)
        .map_err(|e| anyhow::anyhow!("Serialization failed: {}", e))?;

    let contract_name_slug = contract.name.to_lowercase().replace(' ', "_");

    for file in &output_files {
        // Determine subdirectory: baseline/ or contract_specific/ or root
        let subdir = if file.filename.starts_with("manifest") || file.filename.starts_with("summary") {
            contract_output_dir.clone()
        } else if file.suite_name.contains(&contract_name_slug) {
            contract_output_dir.join("contract_specific")
        } else {
            contract_output_dir.join("baseline")
        };
        std::fs::create_dir_all(&subdir)?;

        // The filename from serialize_suite_set includes path components like
        // "order/baseline/data_validity_suite.json" — extract just the basename
        let basename = Path::new(&file.filename)
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or(&file.filename);

        let out_path = subdir.join(basename);
        std::fs::write(&out_path, &file.content)?;
        println!("  ✓ Written: {}", out_path.display());
    }

    Ok(())
}

// ── DQ Run ────────────────────────────────────────────────────────────────────

fn run_dqrun(cli: &Cli) -> Result<()> {
    let src = cli.src.as_ref()
        .ok_or_else(|| anyhow::anyhow!(
            "--src is required for --action dqrun\n\
             Specify the data file(s) to validate (e.g. --src ./data/transactions.csv)"
        ))?;
    let tests_path = cli.tests.as_ref()
        .ok_or_else(|| anyhow::anyhow!(
            "--tests is required for --action dqrun\n\
             Specify the path to GX suite files generated by --action dataquality\n\
             Example: --tests ./expectations/transactions"
        ))?;
    let output_dir = cli.output.as_ref()
        .ok_or_else(|| anyhow::anyhow!(
            "--output is required for --action dqrun\n\
             Specify where to write validation results"
        ))?;

    if cli.contract_type != "greatexpectations" {
        anyhow::bail!("--action dqrun currently only supports --type greatexpectations");
    }

    // Validate src exists
    if !src.exists() {
        anyhow::bail!("Source data path does not exist: {}", src.display());
    }

    // Collect GX suite JSON files from --tests
    let suite_files = collect_source_files(tests_path, cli.recursive)?
        .into_iter()
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("json"))
        .filter(|p| {
            let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
            name.ends_with("_suite.json")
        })
        .collect::<Vec<_>>();

    if suite_files.is_empty() {
        anyhow::bail!(
            "No GX suite files (*_suite.json) found in: {}\n\
             Generate them first with: aytch --action dataquality --src <contracts> --output <tests_dir> --type greatexpectations",
            tests_path.display()
        );
    }

    // Collect data source files from --src
    let data_files = collect_source_files(src, cli.recursive)?
        .into_iter()
        .filter(|p| {
            matches!(
                p.extension().and_then(|e| e.to_str()),
                Some("csv") | Some("json") | Some("xlsx") | Some("xls") | Some("parquet")
            )
        })
        .collect::<Vec<_>>();

    if data_files.is_empty() {
        anyhow::bail!(
            "No supported data files found in: {}\n\
             Supported formats: .csv, .json, .xlsx, .parquet",
            src.display()
        );
    }

    std::fs::create_dir_all(output_dir)?;

    println!("⟳ Running {} GX suite(s) against {} data file(s)", suite_files.len(), data_files.len());
    println!("  Tests:    {}", tests_path.display());
    println!("  Data:     {}", src.display());
    if let Some(contracts) = &cli.contracts {
        println!("  Contracts: {}", contracts.display());
    }
    println!("  Output:   {}", output_dir.display());

    // Build and execute the Python runner script
    let runner_script = build_gx_runner_script(&suite_files, &data_files, output_dir, cli.contracts.as_deref())?;
    let script_path = output_dir.join("_aytch_gx_runner.py");
    std::fs::write(&script_path, &runner_script)?;

    let python_cmd = find_python(cli.python.as_deref())?;
    println!("  Python:   {}", python_cmd);

    let status = std::process::Command::new(&python_cmd)
        .arg(&script_path)
        .status()
        .with_context(|| format!("Failed to execute Python: {}", python_cmd))?;

    let _ = std::fs::remove_file(&script_path);

    if !status.success() {
        anyhow::bail!("GX execution failed with exit code: {:?}", status.code());
    }

    println!("\n✓ GX validation complete. Results written to: {}", output_dir.display());
    Ok(())
}

// ── DQ Run helpers ────────────────────────────────────────────────────────────

/// Find Python executable on PATH, or use the user-specified override.
fn find_python(override_cmd: Option<&str>) -> Result<String> {
    // If the user specified --python, validate it and use it directly.
    if let Some(cmd) = override_cmd {
        if std::process::Command::new(cmd)
            .arg("--version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
        {
            return Ok(cmd.to_string());
        }
        anyhow::bail!(
            "Specified Python executable not found or not executable: {}\n\
             Check the path and ensure Python is installed there.",
            cmd
        );
    }

    // Auto-detect from PATH.
    for cmd in &["python", "python3", "py"] {
        if std::process::Command::new(cmd)
            .arg("--version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
        {
            return Ok(cmd.to_string());
        }
    }
    anyhow::bail!(
        "Python not found on PATH. Install Python 3.9+ and ensure it is on your PATH.\n\
         Alternatively, specify the Python executable with --python <path>.\n\
         Download: https://www.python.org/downloads/"
    )
}

/// Build a Python script that runs GX suites against data files and generates Data Docs HTML
fn build_gx_runner_script(
    suite_files: &[PathBuf],
    data_files: &[PathBuf],
    output_dir: &Path,
    contracts_path: Option<&Path>,
) -> Result<String> {
    let suite_paths_json = serde_json::to_string(
        &suite_files.iter()
            .map(|p| p.to_string_lossy().replace('\\', "/"))
            .collect::<Vec<_>>()
    )?;

    let data_paths_json = serde_json::to_string(
        &data_files.iter()
            .map(|p| p.to_string_lossy().replace('\\', "/"))
            .collect::<Vec<_>>()
    )?;

    let output_dir_str = output_dir.to_string_lossy().replace('\\', "/");
    let contracts_path_repr = contracts_path
        .map(|p| format!("\"{}\"", p.to_string_lossy().replace('\\', "/")))
        .unwrap_or_else(|| "None".to_string());

    Ok(format!(r#"#!/usr/bin/env python3
"""
aytch dqrun -- Great Expectations suite executor with Data Docs
Auto-generated by aytch. Do not edit manually.
"""
import sys
import json
import os
import shutil
from pathlib import Path
from datetime import datetime, timezone

# Fix Windows console encoding
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

# Check great_expectations is installed
try:
    import great_expectations as gx
    import great_expectations.expectations as gxe
    print(f"GX version: {{gx.__version__}}")
except ImportError as e:
    print(f"ERROR: great_expectations is not installed: {{e}}")
    print("Install it with: pip install great-expectations")
    sys.exit(1)

try:
    import pandas as pd
except ImportError:
    print("ERROR: pandas is not installed. Install with: pip install pandas")
    sys.exit(1)

SUITE_FILES = {suite_paths_json}
DATA_FILES = {data_paths_json}
OUTPUT_DIR = Path("{output_dir_str}")
CONTRACTS_PATH = {contracts_path_repr}

def snake_to_pascal(name: str) -> str:
    """Convert expect_column_to_exist -> ExpectColumnToExist"""
    return ''.join(word.capitalize() for word in name.split('_'))

def load_suite(suite_file: str, context) -> tuple:
    """Load a GX ExpectationSuite from JSON and register it with the context."""
    with open(suite_file, 'r', encoding='utf-8') as f:
        suite_dict = json.load(f)

    suite_name = suite_dict.get('name', Path(suite_file).stem)

    # Create suite
    suite = gx.ExpectationSuite(name=suite_name)

    loaded = 0
    skipped = 0
    for exp_dict in suite_dict.get('expectations', []):
        exp_type = exp_dict.get('type', exp_dict.get('expectation_type', ''))
        kwargs = exp_dict.get('kwargs', {{}})
        meta = exp_dict.get('meta', {{}})

        if not exp_type:
            skipped += 1
            continue

        class_name = snake_to_pascal(exp_type)
        try:
            exp_class = getattr(gxe, class_name, None)
            if exp_class is None:
                skipped += 1
                continue
            # Filter kwargs to only those accepted by the class
            import inspect
            sig = inspect.signature(exp_class.__init__)
            valid_params = set(sig.parameters.keys()) - {{'self'}}
            filtered_kwargs = {{k: v for k, v in kwargs.items() if k in valid_params or 'kwargs' in valid_params}}
            exp = exp_class(**filtered_kwargs)
            suite.add_expectation(exp)
            loaded += 1
        except Exception:
            skipped += 1

    # Register suite with context
    try:
        context.suites.add(suite)
    except Exception:
        try:
            context.suites.add_or_update(suite)
        except Exception:
            pass

    return suite, loaded, skipped

def load_dataframe(data_file: Path) -> pd.DataFrame:
    """Load a data file into a pandas DataFrame."""
    ext = data_file.suffix.lower()
    if ext == '.csv':
        return pd.read_csv(data_file)
    elif ext == '.json':
        return pd.read_json(data_file)
    elif ext in ('.xlsx', '.xls'):
        return pd.read_excel(data_file)
    elif ext == '.parquet':
        return pd.read_parquet(data_file)
    else:
        raise ValueError(f"Unsupported format: {{ext}}")

def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    gx_dir = OUTPUT_DIR / "gx"

    # Initialize file-based GX context in output directory
    print(f"Initializing GX context in: {{gx_dir}}")
    context = gx.get_context(mode="file", project_root_dir=str(OUTPUT_DIR))

    all_results = {{
        "run_timestamp": datetime.now(timezone.utc).isoformat(),
        "gx_version": gx.__version__,
        "data_files": [str(f) for f in DATA_FILES],
        "suite_count": len(SUITE_FILES),
        "contracts_path": str(CONTRACTS_PATH) if CONTRACTS_PATH else None,
        "suites": []
    }}

    total_expectations = 0
    total_passed = 0
    total_failed = 0

    for data_file_str in DATA_FILES:
        data_file = Path(data_file_str)
        data_stem = data_file.stem

        print(f"\nLoading data: {{data_file}}")
        try:
            df = load_dataframe(data_file)
            print(f"  Rows: {{len(df)}}, Columns: {{len(df.columns)}}")
        except Exception as e:
            print(f"  ERROR loading data: {{e}}")
            continue

        # Register data source for this file
        ds_name = f"aytch_{{data_stem}}"
        try:
            data_source = context.data_sources.add_pandas(name=ds_name)
        except Exception:
            data_source = context.data_sources.get(ds_name)

        data_asset = data_source.add_dataframe_asset(name=f"{{data_stem}}_asset")
        batch_def = data_asset.add_batch_definition_whole_dataframe(f"{{data_stem}}_batch")

        for suite_file in SUITE_FILES:
            suite_name = Path(suite_file).stem
            print(f"  Running suite: {{suite_name}}")

            try:
                suite, loaded, skipped = load_suite(suite_file, context)
                print(f"    Loaded {{loaded}} expectations ({{skipped}} skipped)")

                # Create validation definition
                vd_name = f"{{data_stem}}_{{suite_name}}"
                try:
                    vd = context.validation_definitions.add(
                        gx.ValidationDefinition(
                            name=vd_name,
                            data=batch_def,
                            suite=suite,
                        )
                    )
                except Exception:
                    vd = context.validation_definitions.get(vd_name)

                # Run validation
                result = vd.run(batch_parameters={{"dataframe": df}})

                stats = result.statistics if hasattr(result, 'statistics') else {{}}
                if isinstance(stats, dict):
                    passed = stats.get('successful_expectations', 0)
                    failed = stats.get('unsuccessful_expectations', 0)
                    exp_total = stats.get('evaluated_expectations', loaded)
                else:
                    passed = getattr(stats, 'successful_expectations', 0)
                    failed = getattr(stats, 'unsuccessful_expectations', 0)
                    exp_total = getattr(stats, 'evaluated_expectations', loaded)

                success = bool(result.success)

                total_expectations += exp_total
                total_passed += passed
                total_failed += failed

                status = "PASSED" if success else "FAILED"
                print(f"    {{status}}: {{passed}}/{{exp_total}} passed")

                # Write per-result JSON
                result_file = OUTPUT_DIR / f"{{data_stem}}_{{suite_name}}_results.json"
                try:
                    result_dict = result.to_json_dict() if hasattr(result, 'to_json_dict') else {{}}
                    with open(result_file, 'w', encoding='utf-8') as f:
                        json.dump(result_dict, f, indent=2, default=str)
                except Exception as e:
                    print(f"    Warning: Could not write result JSON: {{e}}")

                all_results["suites"].append({{
                    "data_file": str(data_file),
                    "suite_name": suite_name,
                    "success": success,
                    "expectations_total": exp_total,
                    "expectations_passed": passed,
                    "expectations_failed": failed,
                    "results_file": str(result_file)
                }})

            except Exception as e:
                print(f"    ERROR: {{e}}")
                all_results["suites"].append({{
                    "data_file": str(data_file),
                    "suite_name": suite_name,
                    "success": False,
                    "error": str(e)
                }})

    # Build Data Docs HTML
    print("\nBuilding Data Docs HTML reports...")
    docs_path = None
    try:
        context.build_data_docs()
        docs_path = OUTPUT_DIR / "gx" / "uncommitted" / "data_docs" / "local_site" / "index.html"
        if docs_path.exists():
            print(f"Data Docs: {{docs_path}}")
        else:
            # Try alternate path
            docs_path = None
            for p in OUTPUT_DIR.rglob("index.html"):
                if "data_docs" in str(p):
                    docs_path = p
                    print(f"Data Docs: {{docs_path}}")
                    break
    except Exception as e:
        print(f"Warning: Could not build Data Docs: {{e}}")
        docs_path = None

    # Write summary
    all_results["total_expectations"] = total_expectations
    all_results["total_passed"] = total_passed
    all_results["total_failed"] = total_failed
    all_results["overall_success"] = total_failed == 0
    all_results["data_docs_path"] = str(docs_path) if docs_path and docs_path.exists() else None

    summary_file = OUTPUT_DIR / "validation_summary.json"
    with open(summary_file, 'w', encoding='utf-8') as f:
        json.dump(all_results, f, indent=2, default=str)

    print(f"\n{{'='*60}}")
    print(f"VALIDATION SUMMARY")
    print(f"{{'='*60}}")
    print(f"Suites run:          {{len(SUITE_FILES)}}")
    print(f"Data files:          {{len(DATA_FILES)}}")
    print(f"Total expectations:  {{total_expectations}}")
    print(f"Passed:              {{total_passed}}")
    print(f"Failed:              {{total_failed}}")
    overall = "ALL PASSED" if total_failed == 0 else f"{{total_failed}} FAILED"
    print(f"Overall:             {{overall}}")
    print(f"Results:             {{OUTPUT_DIR}}")
    print(f"Summary:             {{summary_file}}")
    if docs_path and docs_path.exists():
        print(f"Data Docs HTML:      {{docs_path}}")
        print(f"\nOpen in browser:     file:///{{str(docs_path).replace(chr(92), '/')}}")

    sys.exit(0 if total_failed == 0 else 1)

if __name__ == '__main__':
    main()
"#))
}

// ── File collection ───────────────────────────────────────────────────────────

fn collect_source_files(src: &Path, recursive: bool) -> Result<Vec<PathBuf>> {
    if src.is_file() {
        return Ok(vec![src.to_path_buf()]);
    }
    if src.is_dir() {
        let extensions = ["json", "yaml", "yml", "xml", "xsd", "csv"];
        let mut files = Vec::new();
        collect_files_in_dir(src, &extensions, recursive, &mut files)?;
        if files.is_empty() {
            anyhow::bail!("No supported files found in directory: {}", src.display());
        }
        return Ok(files);
    }
    anyhow::bail!("Source path does not exist: {}", src.display())
}

fn collect_files_in_dir(
    dir: &Path,
    extensions: &[&str],
    recursive: bool,
    files: &mut Vec<PathBuf>,
) -> Result<()> {
    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_file() {
            if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                if extensions.contains(&ext.to_lowercase().as_str()) {
                    files.push(path);
                }
            }
        } else if path.is_dir() && recursive {
            collect_files_in_dir(&path, extensions, recursive, files)?;
        }
    }
    Ok(())
}

// ── Format resolution ─────────────────────────────────────────────────────────

fn resolve_formats(format_str: &str) -> Result<Vec<(OutputFormat, &'static str)>> {
    match format_str.to_lowercase().as_str() {
        "all" => Ok(vec![
            (OutputFormat::Json, "json"),
            (OutputFormat::Yaml, "yaml"),
            (OutputFormat::Xml, "xml"),
            (OutputFormat::Csv, "csv"),
        ]),
        "json" => Ok(vec![(OutputFormat::Json, "json")]),
        "yaml" => Ok(vec![(OutputFormat::Yaml, "yaml")]),
        "xml" => Ok(vec![(OutputFormat::Xml, "xml")]),
        "csv" => Ok(vec![(OutputFormat::Csv, "csv")]),
        other => anyhow::bail!(
            "Unknown --format '{}'. Use: json, yaml, xml, csv, or all",
            other
        ),
    }
}
