from typing import Optional, Any

class DqEngine:
    def __init__(self) -> None: ...
    def set_include_baseline(self, v: bool) -> None: ...
    def set_include_contract_specific(self, v: bool) -> None: ...
    def set_gx_version(self, v: str) -> None: ...
    def generate_from_contract(self, contract: dict[str, Any]) -> dict[str, Any]: ...
    def generate_from_source(
        self,
        content: bytes,
        format_hint: Optional[str] = None,
        source_path: Optional[str] = None,
    ) -> dict[str, Any]: ...
    def write_suite_set(
        self,
        suite_set: dict[str, Any],
        output_dir: str,
        output_format: str = "gx_json",
    ) -> None: ...
    def generate_baseline(self) -> list[dict[str, Any]]: ...
    def serialize_suite_set(
        self,
        suite_set: dict[str, Any],
        output_format: str = "gx_json",
    ) -> list[dict[str, Any]]: ...

__version__: str
