---
- name: Install cephadm dependencies
  apt:
    name:
      - curl
      - python3
      - python3-pip
      - lvm2
      - ceph-common
    state: present
    update_cache: yes

- name: Bootstrap Ceph single-node cluster
  command: cephadm bootstrap --mon-ip {{ ansible_host }} --initial-dashboard-password SuperSecretCeph2026! --allow-fqdn
  args:
    creates: /etc/ceph/ceph.conf
  register: ceph_bootstrap

- name: Enable CephFS (required for MinIO backend)
  command: ceph fs new cephfs cephfs_metadata cephfs_data
  when: ceph_bootstrap.changed

- name: Create CephFS mount point
  file:
    path: /mnt/cephfs
    state: directory

- name: Mount CephFS
  mount:
    path: /mnt/cephfs
    src: "{{ ceph_cluster_name }}-fs:/"
    fstype: ceph
    opts: "name=admin,secretfile=/etc/ceph/ceph.client.admin.keyring"
    state: mounted
